
version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - tylkozapytam

  backend:
    container_name: backend
    build:
      context: ../backend/app
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
        - ./backend/app:/app
    env_file:
        - ../.env.development
    networks:
      - tylkozapytam
    depends_on:
        - db


networks:
  tylkozapytam:
