# Generated by Django 4.1.5 on 2023-01-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_client_user_expert_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="user",
            new_name="client_id",
        ),
        migrations.RenameField(
            model_name="expert",
            old_name="user",
            new_name="expert_id",
        ),
    ]
