# Generated by Django 4.1.5 on 2023-01-18 11:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_expert_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="working_hours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=5),
                blank=True,
                default=list,
                size=3,
            ),
        ),
    ]
