# Generated by Django 4.1.5 on 2023-01-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_user_client_client_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="client_id",
            new_name="client",
        ),
    ]
