# Generated by Django 4.1.5 on 2023-01-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_expert_working_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
    ]
