# Generated by Django 4.1.5 on 2023-01-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_client_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="device_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="expert",
            name="device_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
