# Generated by Django 4.1.5 on 2023-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_client_id_client_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="device_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="expert",
            name="device_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
