# Generated by Django 4.1.5 on 2023-01-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_client_device_type_alter_expert_device_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="device_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="expert",
            name="device_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
