# Generated by Django 4.1.5 on 2023-01-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_expert_working_hours_alter_client_device_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="working_hours",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
