# Generated by Django 4.1.5 on 2023-01-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_expert_working_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expert",
            name="working_hours",
        ),
    ]
