# Generated by Django 4.1.5 on 2023-01-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_expert_category_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="phone_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
