# Generated by Django 4.1.5 on 2023-01-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_expert_working_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="expert_is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
