# Generated by Django 4.1.5 on 2023-01-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_expert_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
