# Generated by Django 4.1.5 on 2023-01-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_client_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expert",
            old_name="expert_id",
            new_name="expert",
        ),
    ]
