# Generated by Django 4.1.5 on 2023-01-24 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_question_expert_id"),
        ("users", "0010_expert_expert_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="ratings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.rating",
            ),
        ),
    ]
