# Generated by Django 4.1.5 on 2023-01-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_rename_expert_id_expert_expert"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expert",
            name="category_choices",
        ),
    ]
