# Generated by Django 4.1.5 on 2023-01-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_expert_ratings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expert",
            name="ratings",
        ),
    ]
