# Generated by Django 4.1.5 on 2023-01-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question_text", models.TextField(max_length=1000)),
                ("answer", models.TextField(max_length=1000)),
                ("question_date", models.DateTimeField(auto_now_add=True)),
                ("answer_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
