# Generated by Django 4.1.5 on 2023-01-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_question_answer_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
