# Generated by Django 4.1.5 on 2023-01-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
