# Generated by Django 4.1.5 on 2023-01-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_question_answer_alter_question_answer_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("call_date", models.DateTimeField(auto_now_add=True)),
                ("call_duration", models.IntegerField(blank=True, null=True)),
                ("call_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "call_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
