# Generated by Django 4.1.5 on 2023-01-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_call"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.DateTimeField(auto_now_add=True)),
                (
                    "tags",
                    models.ManyToManyField(related_name="categories", to="app.tag"),
                ),
            ],
        ),
    ]
