# Generated by Django 4.1.5 on 2023-01-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_category_name_remove_category_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True, null=True, verbose_name=range(1, 6)
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=1000, null=True)),
                ("rating_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
