# Generated by Django 4.1.5 on 2023-02-01 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
