# Generated by Django 4.1.5 on 2023-01-24 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="tags",
        ),
        migrations.AlterField(
            model_name="call",
            name="call_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="call",
            name="call_duration",
            field=models.IntegerField(
                blank=True,
                choices=[(10, 10), (15, 15), (20, 20), (25, 25), (30, 30)],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="call_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scheduled", "Scheduled"),
                    ("answered", "Answered"),
                    ("missed", "Missed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="call_type",
            field=models.CharField(
                blank=True,
                choices=[("Incoming", "Incoming"), ("outgoing", "Outgoing")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
