# Generated by Django 4.1.5 on 2023-02-01 12:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_expert_category_choices"),
        ("app", "0009_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="client",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.client",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="comment",
            field=models.TextField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name="rating",
            name="expert",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.expert",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                default=None,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
