# Generated by Django 4.1.5 on 2023-01-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_expert_working_hours"),
        ("app", "0009_remove_category_tags_alter_call_call_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="client_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.client",
            ),
        ),
    ]
