# Generated by Django 4.1.5 on 2023-01-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_expert_working_hours"),
        ("app", "0010_question_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="client_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.client",
            ),
        ),
    ]
