# Generated by Django 4.1.5 on 2023-02-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_rename_client_rating_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="user",
            new_name="client",
        ),
    ]
