# Generated by Django 4.1.5 on 2023-01-24 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_expert_working_hours"),
        ("app", "0012_alter_question_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="expert_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.expert",
            ),
        ),
    ]
