# Generated by Django 4.1.5 on 2023-01-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_question_expert_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="expert_id",
        ),
    ]
