# Generated by Django 4.1.5 on 2023-01-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_rating_client_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="client_id",
            new_name="user_id",
        ),
    ]
