# Generated by Django 4.1.5 on 2023-01-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_rename_client_id_rating_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="comment",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
