# Generated by Django 4.1.5 on 2023-01-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_rating_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="tags",
            field=models.ManyToManyField(blank=True, to="app.tag"),
        ),
    ]
