# Generated by Django 4.1.5 on 2023-02-01 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_expert_category_choices"),
        ("app", "0017_alter_rating_expert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.client"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.expert"
            ),
        ),
    ]
