# Generated by Django 4.1.5 on 2023-01-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="tags",
        ),
    ]
