# Generated by Django 4.1.5 on 2023-01-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_remove_category_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tags",
            field=models.ManyToManyField(blank=True, to="app.tag"),
        ),
    ]
