# Generated by Django 4.1.5 on 2023-01-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_category_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
